name: app
description: "A Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  flutter_screenutil: ^5.9.3
#  bloc: ^8.1.4
#  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
#  lottie: ^3.1.2
#  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
#  smooth_page_indicator: ^1.2.0+3
#  chip_list: ^3.1.0
#  url_launcher: ^6.3.0
  quick_log: ^5.4.1
#  flutter_facebook_auth: ^7.0.1
#  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
#  email_validator: ^3.0.0
#  pull_to_refresh: ^2.0.0
#  salomon_bottom_bar: ^3.3.2
#  awesome_drawer_bar: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/01_breakfast/
    - assets/images/02_lunch/
    - assets/images/03_salad/
    - assets/images/04_sauces/
    - assets/images/05_sweets/
    - assets/images/06_drinks/
    - assets/lottie/
    - assets/svg/
    - assets/fonts/


  uses-material-design: true

  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/Tajawal.ttf

    - family: title_font
      fonts:
        - asset: assets/fonts/Cairo.ttf

#    - family: font003
#      fonts:
#        - asset: assets/fonts/JotiOne-Regular.ttf