final lunch = <Map<String, dynamic>>[  {
  'level': 'سهل',
  'prep_time': 10,
  'cook_time': 10,
  'stats': false,
  'ingredients_count': 7,
  'steps_count': 4,
  'title_en': 'Place holder',
  'title_ar': 'Place holder',
  'image': '',
  'ingredients': [
    {'item': '', 'quantity': ''},
    {'item': '', 'quantity': ''},
    {'item': '', 'quantity': ''},
    {'item': '', 'quantity': ''},
    {'item': '', 'quantity': ''},
    {'item': '', 'quantity': ''},
    {'item': '', 'quantity': ''},
  ],
  'steps': [
    '',
    '',
    '',
    '',
  ],
},];
